ARG PYTHON_VERSION
ARG DEBIAN_VERSION

FROM python:${PYTHON_VERSION}-slim-${DEBIAN_VERSION}


# Install dependencies
RUN apt-get update \
    && apt-get install -y \
        build-essential \
        curl \
        g++ \
	    git \
        make \
        python3-venv \
        software-properties-common

# Add NodeSource PPA to get Node.js 18.x
RUN curl -fsSL https://deb.nodesource.com/setup_19.x | bash -

# Install Node.js 19.x
RUN apt-get update \
    && apt-get install -y nodejs

RUN npx dalai alpaca install 7B --home=/opt/magic_mirror/dalai

RUN npm install -g nodemon